services:
  - type: web
    name: leetcode-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn backend.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: backend.settings
      - key: PYTHON_VERSION
        value: 3.12.3
      - key: SECRET_KEY
        value: your-secret-key-here
      - key: DEBUG
        value: False
